---


- hosts: all
  become: true
  tasks: 

  - name: Update repository index
    apt:
      update_cache: yes

  - name: Installing apache2 package
    apt: 
      name: apache2
      state: latest
